### ISSUE TITLE
Automatically fallback to default CPU execution if a parfor cannot be offloaded to a SYCL GPU device

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba#16]
Currently for any NumPy operation or parfor that is not offloadable to a SYCL GPU we throw an exception. A more optimal behavior from a user experience will be to fallback to the default Numba behavior and run the code on the CPU. 

Closed when PR #8 gets merged.

**Comment by reazulhoque** [comment]
PR https://github.com/IntelPython/numba/pull/8 got merged. Closing this issue.
