### ISSUE TITLE
Error reported when Numba-PyDPPL execution begins

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba#25]
An error message is reported as soon as Numba-PyDPPL executions begins. But the program continues execution.

DP_Glue Error: -1 (Failed inside get_first_device) on Line 356 in /localdisk/work/adarshyoga/software/miniconda3/envs/build-env/conda-bld/pydppl_1598384540212/work/backends/source/dppl_opencl_interface.c
DPPL-WARNING - No CPU device

**Comment by diptorupd** [comment]
Closing this issue as lot's of changes have taken place with Numba-DPPY's back end and we are not using ocldrv anymore.
