### ISSUE TITLE
Integration of dpctl with Numba

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba#46]
This ticket is to track the changes to Numba to integrate with the new Sycl interface added to dpCtrl.

**Add a new compilation path using `dppl` alongwith retaining the `dppl.ocldrv` path**
1. Create a new flag to switch to using `dppl` and DPC++ runtime in the compiler pipeline.
2. The default compilation of Numba-Pydppl will be `dppl` and not use \`ddpl.ocldrv`.
3. dppl.ocldrv is to be marked as depracated and removed in next release.

**Insert equivalents of dppl.ocldrv calls using the new `dppl Cython module**

**Integrate Todd's numba.dppl.dparray**

**Add LLVM builder calls to new libDPPLSyclInterface.so library calls inside lowerer. The calls will be equivalent to the calls that are there presently for libDPPLOpenCLInterface.so**

**Comment by PokhodenkoSA** [comment]
@diptorupd Can this issue be closed or braking down to smaller issues?
As I understand some tasks from the issue was implemented in beta10 milestone.

**Comment by diptorupd** [comment]
Closing as most of the work for DPC++ integration is completed in beta 10. The pending task of `dparray` integration is tracked in #75
