### ISSUE TITLE
Clean differences with Numba 0.51.2 we did not do

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba#51]
During merge with Numba 0.51.2 like #50 there could be changes that are not in upstream Numba and was not added by us.

This code could be searched by showing all diffs and see who are author of the code. If author is not from IntelPython then code should be reverted to upstream Numba code.

**Comment by diptorupd** [comment]
@PokhodenkoSA @reazulhoque already started some of the changes and has created the initial set of patches.
