### ISSUE TITLE
CPU dispatcher should be moved back

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/numba#55]
## Feature request

CPU dispatcher was moved from numba/core/registry.py to avoid circular import. It should be moved back to it's original place.

**Comment by diptorupd** [comment]
@reazulhoque can you check if this issue is still relevant? And, should this belong to numba or numba-dppy?

**Comment by PokhodenkoSA** [comment]
CPU dispatcher was returned to the same as in upstream.
