### ISSUE TITLE
Which compiler to use for SPIRV code

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba#74]
When I made a CI I have activated oneAPI compiler to build SPIRV code here: https://github.com/IntelPython/numba/blob/ec8862c8860185b203966a115942dd5b9b6380a2/buildscripts/condarecipe.pydppl/build.sh#L9

Should it be onaAPI compiler or LLVM compiler is also ok?

**Comment by reazulhoque** [comment]
I think both is ok but to be safe let's keep using oneAPI compiler.
